### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by jcoyne** [samvera/hydra-head#201]
In production mode, this error is raised:

```
ubuntu@ip-10-188-58-230:/opt/tufts-image-library$ bundle exec rails c production
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_PUBLIC
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:5: warning: previous definition of PERMISSION_TEXT_VALUE_PUBLIC was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: already initialized constant Hydra::AccessControls::AccessRight::PERMISSION_TEXT_VALUE_AUTHENTICATED
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:6: warning: previous definition of PERMISSION_TEXT_VALUE_AUTHENTICATED was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:9: warning: previous definition of VISIBILITY_TEXT_VALUE_PUBLIC was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_EMBARGO
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:10: warning: previous definition of VISIBILITY_TEXT_VALUE_EMBARGO was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_LEASE
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:11: warning: previous definition of VISIBILITY_TEXT_VALUE_LEASE was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-acce/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_AUTHENTICATED
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:12: warning: previous definition of VISIBILITY_TEXT_VALUE_AUTHENTICATED was here
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: already initialized constant Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PRIVATE
/usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/access_right.rb:13: warning: previous definition of VISIBILITY_TEXT_VALUE_PRIVATE was here
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
    from /usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/embargoable.rb:7:in `<module:Embargoable>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/embargoable.rb:3:in `<module:AccessControls>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/embargoable.rb:2:in `<module:Hydra>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/hydra-access-controls-7.2.0/app/models/concerns/hydra/access_controls/embargoable.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:443:in `load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:443:in `block in load_file'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:633:in `new_constants_in'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:442:in `load_file'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:342:in `require_or_load'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:307:in `depend_on'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:225:in `require_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:467:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:467:in `block in eager_load!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:465:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:465:in `eager_load!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/engine.rb:346:in `eager_load!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/application/finisher.rb:58:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /usr/local/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
    from /usr/local/lib/ruby/gems/2.1.0/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
    from /opt/tufts-image-library/config/environment.rb:5:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:92:in `preload'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:140:in `serve'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
    from /usr/local/lib/ruby/gems/2.1.0/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
ubuntu@ip-10-188-58-230:/opt/tufts-image-library$ 

```

**Comment by jayanthdeejay** [comment]
https://stackoverflow.com/questions/34316585/how-can-i-run-the-ruby-on-rails-console-in-production-without-executing-spring
